# Generated by Django 5.1.4 on 2024-12-20 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='current_company',
        ),
        migrations.RemoveField(
            model_name='application',
            name='current_role',
        ),
        migrations.RemoveField(
            model_name='application',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='application',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='application',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='application',
            name='portfolio_url',
        ),
    ]
