# Generated by Django 4.2.17 on 2024-12-21 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0003_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='current_company',
            field=models.CharField(default='abc company', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='current_role',
            field=models.CharField(default='software engineer', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='experience_years',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='application',
            name='skills',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('interviewed', 'Interviewed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
    ]
