version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=simplejbdb
      - POSTGRES_USER=simplejbdb_user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py seed_data &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=simplejbdb
      - DB_USER=simplejbdb_user
      - DB_PASS=password
      - DEBUG=1
    depends_on:
      - db

  frontend:
    build: ./simplejbapp
    volumes:
      - ./simplejbapp:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    depends_on:
      - backend

volumes:
  postgres_data: 