version: '3.8'

services:
  frontend:
    build: ./simplejbapp
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000/api
    depends_on:
      - backend
    volumes:
      - ./simplejbapp:/app:delegated
      - frontend_node_modules:/app/node_modules
      - frontend_next:/app/.next

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,backend
      - DATABASE_URL=postgres://postgres:postgres@db:5432/simplejb
    depends_on:
      - db
    volumes:
      - ./backend:/app:delegated

  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=simplejb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"

volumes:
  postgres_data:
  frontend_node_modules:
  frontend_next: